# Generated by Django 3.2.9 on 2022-01-18 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=64)),
                ('email_address', models.CharField(max_length=64)),
                ('user_date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
