# Generated by Django 3.2.9 on 2022-01-25 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estudent_startapp', '0006_auto_20220125_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Needs',
            new_name='Need',
        ),
        migrations.RenameModel(
            old_name='Savings',
            new_name='Saving',
        ),
        migrations.RenameModel(
            old_name='Wants',
            new_name='Want',
        ),
    ]
