# Generated by Django 3.2.9 on 2022-01-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudent_startapp', '0008_auto_20220127_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='needs',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='savings',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='wants',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
