# Generated by Django 3.2.9 on 2022-02-07 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estudent_startapp', '0010_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='edit_date_budget',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
