# Generated by Django 3.2.9 on 2022-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudent_startapp', '0012_alter_budget_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date_due',
            field=models.DateField(blank=True, default=None, help_text='Please format YY-MM-DD', null=True),
        ),
    ]
