# Generated by Django 3.2.9 on 2022-02-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudent_startapp', '0013_alter_goal_date_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='id',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
