# Generated by Django 3.2.9 on 2022-02-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudent_startapp', '0014_auto_20220221_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False),
        ),
    ]
