# Generated by Django 3.2.9 on 2022-02-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudent_startapp', '0015_alter_goal_goal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal_id',
            new_name='id',
        ),
    ]
