# Generated by Django 3.2.9 on 2022-03-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudent_startapp', '0016_rename_goal_id_goal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='leftover_need_budget',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='want',
            name='leftover_want_budget',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
