# Generated by Django 3.2.9 on 2022-03-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudent_startapp', '0017_auto_20220301_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='month_int',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
